name = "GIBBON"

[folders]
path = [
    "lib",
]
test = [
    "tests",
]

[project]
startup-files = [
    "installGibbon.m",
]

[[package]]
configuration-name = "Package"
name = "GIBBON"
display-name = "GIBBON"
version = "3.6.0"
id = "37322aae-8e6e-41c9-8125-ddd08b08de58"
unique-id = "37322aae-8e6e-41c9-8125-ddd08b08de58"
output-file-name = "gibbon.mltbx"
output-folder = "."
supported-platforms = [
    "windows",
    "linux",
    "macos",
]

use-license-bsd = false
provider.name = "Kevin M. Moerman"
provider.email = "kevin.moerman@nuigalway.ie"
provider.organization = "gibbonCode"
summary = "GIBBON (The Geometry and Image-Based Bioengineering add-ON) is an open-source MATLAB toolbox for image and geometry processing and visualization"
description = "GIBBON includes an array of own tools and is interfaced with free open source software such as TetGen, for robust tetrahedral meshing, and FEBio for finite element analysis. The combination provides a highly flexible image-based modelling environment and enables advanced inverse finite element analysis."
package-root = "/"
required-additional-software = [
    {name = "FEBio", download-url = "https://febio.org/downloads", license-url = "https://febio.org/about/licensing", platform = [
    "Windows",
    "Linux",
    "Mac",
]},
]
release-compatibility = "20.2.* - 26.2.*"
