% DOCS
%
% Files
%   DEMO_additional_colormaps                                      - DEMO_additional_colormaps
%   DEMO_create_run_import_FEBIO_spheres                           - DEMO_create_run_import_FEBIO_spheres
%   DEMO_create_run_import_FEBIO_spheres_pressure                  - DEMO_create_run_import_FEBIO_spheres_pressure
%   DEMO_create_run_import_FEBIO_spheres_traction                  - DEMO_create_run_import_FEBIO_spheres_traction
%   DEMO_febio_0001_cube_uniaxial                                  - DEMO_febio_0001_cube_uniaxial
%   DEMO_febio_0002_beam_force                                     - DEMO_febio_0002_beam_force
%   DEMO_febio_0003_beam_bending                                   - DEMO_febio_0003_beam_bending
%   DEMO_febio_0004_beam_twist                                     - DEMO_febio_0004_beam_twist
%   DEMO_febio_0005_cube_tension_compression_shear                 - DEMO_febio_0005_cube_tension_compression_shear
%   DEMO_febio_0006_sphere_indentation                             - DEMO_febio_0006_sphere_indentation
%   DEMO_febio_0007_sphere_sliding                                 - DEMO_febio_0007_sphere_sliding
%   DEMO_febio_0008_cube_body_load                                 - DEMO_febio_0008_cube_body_load
%   DEMO_febio_0009_cube_discrete_springs                          - DEMO_febio_0009_cube_discrete_springs
%   DEMO_febio_0010_trabeculae_compression                         - DEMO_febio_0010_trabeculae_compression
%   DEMO_febio_0011_cube_multi_generation                          - DEMO_febio_0011_cube_multi_generation
%   DEMO_FEBio_active_contraction_01                               - DEMO_FEBio_active_contraction_01
%   DEMO_FEBio_active_responsive_interface                         - DEMO_FEBio_active_responsive_interface
%   DEMO_FEBio_AnyBody_force_analysis                              - DEMO_FEBio_AnyBody_force_analysis
%   DEMO_FEBio_bar_force                                           - DEMO_FEBio_bar_force
%   DEMO_FEBio_bar_soft_sphere_indentation                         - DEMO_FEBio_bar_soft_sphere_indentation
%   DEMO_FEBio_bar_sphere_indentation                              - DEMO_FEBio_bar_sphere_indentation
%   DEMO_FEBio_bar_sphere_indentation_multi_generation             - DEMO_FEBio_bar_sphere_indentation_multi_generation
%   DEMO_FEBio_bar_sphere_indentation_multi_step                   - DEMO_FEBio_bar_sphere_indentation_multi_step
%   DEMO_FEBio_bar_twist                                           - DEMO_FEBio_bar_twist
%   DEMO_FEBio_beam_bending                                        - DEMO_FEBio_beam_bending
%   DEMO_FEBio_beam_L_force                                        - DEMO_FEBio_beam_L_force
%   DEMO_FEBio_block_biaxial_loading_stiffness_analysis            - DEMO_FEBio_block_biaxial_loading_stiffness_analysis
%   DEMO_FEBio_block_tension_compression_shear                     - DEMO_FEBio_block_tension_compression_shear
%   DEMO_FEBio_block_uniaxial_compression                          - DEMO_FEBio_block_uniaxial_compression
%   DEMO_FEBio_block_uniaxial_compression_biphasic_ramp_hold       - DEMO_FEBio_block_uniaxial_compression_biphasic_ramp_hold
%   DEMO_FEBio_block_uniaxial_compression_fibre_reinforced         - DEMO_FEBio_block_uniaxial_compression_fibre_reinforced
%   DEMO_FEBio_block_uniaxial_compression_stiffness_analysis       - DEMO_FEBio_block_uniaxial_compression_stiffness_analysis
%   DEMO_FEBio_block_uniaxial_compression_viscoelastic_load_unload - DEMO_FEBio_block_uniaxial_compression_dynamic_viscoelastic_load_unload
%   DEMO_FEBio_block_uniaxial_compression_viscoelastic_ramp_hold   - DEMO_FEBio_block_uniaxial_compression_dynamic_viscoelastic_ramp_hold
%   DEMO_FEBio_continuous_fibre_distribution                       - DEMO_FEBio_continuous_fibre_distribution.m
%   DEMO_FEBio_cube_multi_generation                               - DEMO_FEBio_cube_multi_generation
%   DEMO_FEBio_cube_multi_step                                     - DEMO_FEBio_cube_multi_step
%   DEMO_FEBio_cube_tension                                        - DEMO_FEBio_cube_tension
%   DEMO_FEBio_cube_viscoelastic_aniso                             - DEMO_FEBio_cube_viscoelastic_aniso
%   DEMO_FEBio_cylinder_embedded_indentor_01                       - DEMO_FEBio_cylinder_embedded_indentor_01
%   DEMO_FEBio_cylinder_spherical_head_indentor                    - DEMO_FEBio_cylinder_spherical_head_indentor
%   DEMO_FEBio_disc_probe_indentation                              - DEMO_FEBio_disc_probe_indentation
%   DEMO_FEBio_hexLattice_compression                              - DEMO_FEBio_hexLattice_compression
%   DEMO_FEBio_iFEA_uniaxial_01                                    - DEMO_FEBio_iFEA_uniaxial_01
%   DEMO_FEBio_iFEA_uniaxial_transiso_01                           - DEMO_FEBio_iFEA_uniaxial_transiso_01.m
%   DEMO_FEBio_iFEA_uniaxial_transiso_02                           - DEMO_FEBio_iFEA_uniaxial_transiso_02.m
%   DEMO_FEBio_iFEA_uniaxial_transiso_03                           - DEMO_FEBio_iFEA_uniaxial_transiso_02.m
%   DEMO_FEBio_layered_spatvar                                     - DEMO_layered_spatvar
%   DEMO_FEBio_multi_scale_analysis                                - DEMO_FEBio_multi_scale_analysis
%   DEMO_FEBio_multigen_interface_active                           - DEMO_FEBio_multigen_interface_active
%   DEMO_FEBio_skin_sphere_indentation                             - DEMO_FEBio_skin_sphere_indentation
%   DEMO_FEBio_skin_sphere_indentation_tet4_vs_tet10               - DEMO_FEBio_skin_sphere_indentation_tet4_vs_tet10
%   DEMO_FEBio_slab_displacement_loading_01                        - DEMO_slab_displacement_loading_01
%   DEMO_FEBio_slab_pressure_loading_01                            - DEMO_FEBio_slab_pressure_loading_01
%   DEMO_FEBio_slab_pressure_loading_02                            - DEMO_FEBio_slab_pressure_loading_02
%   DEMO_FEBio_slab_pressure_loading_03                            - DEMO_FEBio_slab_pressure_loading_03
%   DEMO_FEBio_spatially_varying_material_parameters               - DEMO_spatially_varying_material_parameters
%   DEMO_FEBio_strip_multi_step_clamp                              - DEMO_FEBio_strip_multi_step_clamp
%   DEMO_FEBio_tongue                                              - DEMO_FEBio_tongue
%   DEMO_FEBio_trabeculae_compression                              - DEMO_FEBio_trabeculae_compression
%   DEMO_FEBio_vessel_fibre_mapping                                - DEMO_FEBIO_vessel_fibre_mapping
%   DEMO_FEBio_XML_replacing_node_field                            - DEMO_FEBio_XML_replacing_node_field
%   DEMO_femur_STL_surface_improvement                             - DEMO_femur_STL_surface_improvement.m
%   DEMO_geodesic_remeshing                                        - DEMO_geodesic_remeshing
%   DEMO_import_FEB_export_INP                                     - DEMO_import_FEB_export_INP
%   DEMO_imx_levelset_surface_compare                              - DEMO_imx_levelset_surface_compare
%   DEMO_MixedTetHexMeshing                                        - DEMO_MixedTetHexMeshing
%   DEMO_MixedTetHexMeshing_torus                                  - DEMO_MixedTetHexMeshing_torus
%   DEMO_surface_smooth_methods                                    - DEMO_surface_smooth_methods
%   DEMO_tetGen_mesh_sizing_function_1                             - DEMO_tetGen_mesh_sizing_function_1
%   GIBBON_product_page                                            - GIBBON: A Geometry and Image-Based Bioengineering Add-on for MATLAB
%   HELP_addBoundaryLevel_FEB                                      - addBoundaryLevel_FEB
%   HELP_addConstraintsLevel_FEB                                   - addConstraintsLevel_FEB
%   HELP_addContactLevel_FEB                                       - addContactLevel_FEB
%   HELP_addControlLevel_FEB                                       - addControlLevel_FEB
%   HELP_addGeometryLevel_FEB                                      - addGeometryLevel_FEB
%   HELP_addGLobalsLevel_FEB                                       - addGlobalsLevel_FEB
%   HELP_addMatAxisFibreElementData_FEB                            - addMatAxisFibreElementData_FEB
%   HELP_adjacentdircount                                          - adjacentdircount
%   HELP_affineTransformationMatrixDirect                          - affineTransformationMatrixDirect
%   HELP_anim8                                                     - anim8
%   HELP_bias_nodes1d                                              - bias_nodes1d
%   HELP_biharmonicSplineInterpolation                             - biharmonicSplineInterpolation
%   HELP_box_indices                                               - box_indices
%   HELP_cap_patchcylinder                                         - cap_patchCylinder
%   HELP_cart2im                                                   - cart2im
%   HELP_cell2txtfile                                              - cell2txtfile
%   HELP_cellEig                                                   - cellEig
%   HELP_cFigure                                                   - cFigure
%   HELP_checkerBoard3D                                            - checkerBoard3D
%   HELP_constrainedDelaunayTetGen                                 - constrainedDelaunayTetGen
%   HELP_dcmFolder2MATobject                                       - dcmFolder2MATobject
%   HELP_discQuadMesh                                              - discQuadMesh
%   HELP_edgeListToCurve                                           - edgeListToCurve
%   HELP_efw                                                       - efw
%   HELP_element2HexLattice                                        - element2HexLattice
%   HELP_element2lattice                                           - element2lattice
%   HELP_element2patch                                             - element2patch
%   HELP_ellipsoidFit_centered                                     - HELP_ellipsoidFit_centered
%   HELP_euler2DCM                                                 - HELP_euler2DCM
%   HELP_evenlySampleCurve                                         - evenlySampleCurve
%   HELP_export_INP                                                - export_INP
%   HELP_export_STL_txt                                            - export_STL_txt
%   HELP_febioStruct2xml                                           - febioStruct2xml
%   HELP_febioStructTemplate                                       - febioStructTemplate
%   HELP_filletCurve                                               - filletCurve
%   HELP_foamWrap                                                  - foamWrap
%   HELP_gaborCoil                                                 - gaborCoil
%   HELP_geoSphere                                                 - geoSphere
%   HELP_gpatch                                                    - gpatch
%   HELP_graphicsModels                                            - graphicsModels
%   HELP_hemiSphereCylMesh                                         - hemiSphereCylMesh
%   HELP_hemiSphereRegionMesh                                      - hemiSphereRegionMesh
%   HELP_hessianScalar                                             - hessianScalar
%   HELP_hex2tet                                                   - hex2tet
%   HELP_hexMeshBox                                                - hexMeshBox
%   HELP_hexMeshCubeSphere                                         - PLOT SETTINGS
%   HELP_hexMeshSphere                                             - hexMeshSphere
%   HELP_honeyCombMesh                                             - honeyCombMesh
%   HELP_im2cart                                                   - im2cart
%   HELP_im2patch                                                  - im2patch
%   HELP_import_FEB                                                - import_FEB
%   HELP_import_INP                                                - import_INP
%   HELP_import_off                                                - import_off
%   HELP_import_STL                                                - import_STL
%   HELP_import_STL_bin                                            - import_STL_bin
%   HELP_import_STL_txt                                            - import_STL_txt
%   HELP_importAnyBodyOutput                                       - importAnyBodyOutput
%   HELP_imx                                                       - imx
%   HELP_ind2patch                                                 - ind2patch
%   HELP_interp1_ND                                                - interp1_ND
%   HELP_interp_spherical                                          - interp_spherical
%   HELP_joinElementSets                                           - joinElementSets
%   HELP_linspacen                                                 - linspacen
%   HELP_meshView                                                  - meshView
%   HELP_minDist                                                   - minDist
%   HELP_minPolyTwist                                              - minPolyTwist
%   HELP_multiRegionTriMesh2D                                      - multiRegionTriMesh2D
%   HELP_multiRegionTriMeshUneven2D                                - multiRegionTriMesh2D
%   HELP_numReplace                                                - numReplace
%   HELP_parLimNat                                                 - parLimNat
%   HELP_patch2Im                                                  - patch2Im
%   HELP_patch2STL                                                 - patch2STL
%   HELP_patch_dual                                                - patch_dual
%   HELP_patchcylinder                                             - patchcylinder
%   HELP_patchEdge2Im                                              - patch2EdgeIm
%   HELP_patchTorus                                                - patchTorus
%   HELP_platonic_solid                                            - platonic_solid
%   HELP_pointLocationTR                                           - pointLocationTR
%   HELP_pointSetDistMap                                           - pointSetDistMap
%   HELP_pointSetPrincipalDir                                      - HELP_pointSetPrincipalDir
%   HELP_polyExtrude                                               - polyExtrude
%   HELP_polyLoftLinear                                            - polyExtrude
%   HELP_polyRevolve                                               - polyRevolve
%   HELP_polySet2Im                                                - polySet2Im
%   HELP_polyTube                                                  - polyTube
%   HELP_quad2tri                                                  - quad2tri
%   HELP_quadBox                                                   - quadBox
%   HELP_quadSphere                                                - quadSphere
%   HELP_quiver3Dpatch                                             - quiver3Dpatch
%   HELP_quiverVec                                                 - quiverVec
%   HELP_regionTriMesh2D                                           - regionTriMesh2D
%   HELP_regionTriMesh3D                                           - regionTriMesh3D
%   HELP_regionTriMeshRand2D                                       - regionTriMeshRand2D
%   HELP_resampleColormap                                          - resampleColormap
%   HELP_rgbImage2ColorMap                                         - rgbImage2ColorMap
%   HELP_rhombicDodecahedron                                       - rhombicDodecahedron
%   HELP_rhombicDodecahedronMesh                                   - rhombicDodecahedronMesh
%   HELP_rigidTransformationMatrixDirect                           - rigidTransformationMatrixDirect
%   HELP_runTetGen                                                 - runTetGen
%   HELP_sampleCurveEvenly                                         - sampleCurveEvenly
%   HELP_set_mat_par_FEBIO                                         - set_mat_par_FEBIO
%   HELP_simplexImIntersect                                        - simplexImIntersect
%   HELP_sliceViewer                                               - sliceViewer
%   HELP_splitCurveSetMesh                                         - splitCurveSetMesh
%   HELP_stanford_bunny                                            - stanford_bunny
%   HELP_subCurve                                                  - subCurve
%   HELP_subEdge                                                   - subEdge
%   HELP_subHex                                                    - subHex
%   HELP_subQuad                                                   - subQuad
%   HELP_subTet                                                    - subTet
%   HELP_subtri                                                    - subtri
%   HELP_subTriCentre                                              - subTriCentre
%   HELP_subTriDual                                                - subTriDual
%   HELP_subTriLocal                                               - subTriLocal
%   HELP_sweepLoft                                                 - sweepLoft
%   HELP_tesIND                                                    - tesIND
%   HELP_testGibbon                                                - testGibbon
%   HELP_tet2hex                                                   - tet2hex
%   HELP_tet4_tet10                                                - tet4_tet10
%   HELP_tetVolMeanEst                                             - tetVolMeanEst
%   HELP_textImage                                                 - textImage
%   HELP_tri2quad                                                  - tri2quad
%   HELP_triMeshEquilateral                                        - triMeshEquilateral
%   HELP_triplyPeriodicMinimal                                     - triplyPeriodicMinimal
%   HELP_triPolyDualRefine                                         - triPolyDualRefine
%   HELP_triSurf2Im                                                - triSurf2Im
%   HELP_triSurfCentroid                                           - triSurfCentroid
%   HELP_triSurfRemoveThreeConnect                                 - triSurfRemoveThreeConnect
%   HELP_triSurfSetDist                                            - triSurfSetDist
%   HELP_uiThreshErode                                             - uiThreshErode
%   HELP_vcw                                                       - vcw
%   HELP_vectorOrthogonalPair                                      - vectorOrthogonalPair
%   HELP_viewFourthOrderTensor                                     - viewFourthOrderTensor
%   HELP_voronoiDiagramEven2D                                      - voronoiDiagramEven2D
%   obj_DEMO_FEBio_iFEA_uniaxial_01                                - Unnormalize and constrain parameters
%   obj_DEMO_FEBio_iFEA_uniaxial_transiso_01                       - Unnormalize and constrain parameters
%   obj_DEMO_FEBio_iFEA_uniaxial_transiso_02                       - Unnormalize and constrain parameters
